[13.0][ADD] added new module l10n_do_ncf_validation
indexa-git/l10n_do_currency_update pull request #52
Opened 2020-12-11 02:54 UTC by jlopezg

2020-12-11 13:18 UTC, CarlosRamirezT approved these changes
LGTM!

2020-12-14 09:57 UTC, andrp92 requested changes

2020-12-14 09:57 UTC, andrp92 commented on l10n_do_ncf_validation/data/ir_config_parameter_data.xml
> +    <record id="l10n_do_ncf_validation_api_url" model="ir.config_parameter">
Agregar propiedad  ```forcecreate="0"``` para evitar integrityErrorr. [REF](https://github.com/odoo-dominicana/l10n-dominicana/pull/698/files)

2020-12-14 09:57 UTC, andrp92 commented on l10n_do_ncf_validation/data/ir_config_parameter_data.xml
> +    <record id="l10n_do_ncf_validation_api_token" model="ir.config_parameter">
Agregar propiedad  ```forcecreate="0"``` para evitar integrityErrorr. [REF](https://github.com/odoo-dominicana/l10n-dominicana/pull/698/files)

2020-12-14 14:52 UTC, mamcode approved these changes
Technical review :+1:

2020-12-14 14:52 UTC, mamcode commented on l10n_do_ncf_validation/models/account_move.py
> +        if not ncf or not len(ncf) in (11, 13) or ncf[0] not in ("B", "E"):
```suggestion
        if not ncf or len(ncf) not in (11, 13) or ncf[0] not in ("B", "E"):
```
Me parece que así es mas agradable a la vista. Pero la forma actual igual hace lo que se requiere.

2020-12-16 15:53 UTC, merged